### ISSUE TITLE
OperationsClient

### ISSUE THREAD

**Issue by DavCardenas** [DavCardenas/Air_Hockey_Sockets#14]
Cuando se esta leyendo en lugar de imprimir, asignar al singlenton los valores que llegan, hay que condicionar para saber quien es quien en el singlenton. las condiciones pueden ser con respecto al nombre almacenado inicialmente en el singlenton para corroborar quien soy.

**Comment by AlvaroHernandezM** [comment]
en el singlenton del cliente, estoy comparando que si el esta en begin true, entonces de una vez se sabe que es el de la izquierda y almacena las variables que tiene el dataGame
